version: '3.3'

services:
  app:
    build: .
    container_name: app
    entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    environment: # template do dockerize
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - type: bind
        source: .
        target: /var/www
    networks:
      - app-network
    depends_on:
      - db
      - redis

  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always # sempre que parar ou cair ele restarta
    tty: true # ele fala que a gente pode entrar de forma iterativa no container
    ports:
      - "8000:80"
    volumes:
      - type: bind
        source: .
        target: /var/www
    networks:
      - app-network
    depends_on:
      - app

  db:
    build: .docker/mysql
    command: --innodb-use-native-aio=0 # esse comando serve para funcionar independente do disco ou sistema operacional, esse problema esta relacionado a tipos de dados e arquivos
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment: # Quando a imagem subir ele ja cria um banco de dados com nome laravel e usuario root root e senha root
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network

  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
